# PHP

phpfpm:
  restart: always
  extends:
    file: php-fpm-7.yml
    service: phpfpm
  links:
    - db:db

# NGINX
nginx:
  restart: always
  image: nginx
  ports:
    - "8000:80"
  links:
    - phpfpm:phpfpm
  volumes:
    - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./app:/var/www/html
    - ./log/nginx:/var/log/nginx

# MYSQL
db:
  restart: always
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: database
  volumes:
    - ./mysql/databases:/var/lib/mysql
    - ./log/mysql:/var/log/mysql

#  - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
